### ISSUE TITLE
When the scene is large, I can’t move the camera freely to see the detials

### ISSUE THREAD

**Issue by engineerhe** [CesiumGS/cesium-unity#164]
When the scene is small, I can move the camera freely. When the scene is large, I can’t move the camera to see some details in the scene view.And the 3dtiles url as follows:
http://61.146.36.148:8088/zhanjiang_gisdata/tileset.json

**Comment by j9liu** [comment]
Hi @engineerhe,

Unity is not configured to navigate large-scale applications by default, but you can configure the Editor camera's settings so that it moves faster in the scene.

Go to the toolbar under the Scene view, then click on the camera icon:
![image](https://user-images.githubusercontent.com/32226860/210590486-a09ed6a9-cbea-4942-82f6-a8b5ceef03fe.png)

This will bring up a menu where you can change the clipping planes and speed of the camera. You can increase the camera speed as needed so that the camera isn't so slow.
![image](https://user-images.githubusercontent.com/32226860/210590664-1e90781a-9ca4-474e-9a1b-d1a26bcfe88b.png)

Please let me know if this helps, or if I've misunderstood your issue.

**Comment by engineerhe** [comment]
@j9liu Firstly,thank you very much for your answer. Maybe i dont not have made my meaning clear. I know that you can set the scene camera near and far clipping planes, and then view the scene closely by shortcut keys W, A, S and D.But what I want to know is whether I can view the scene freely through the mouse wheel, because when the scene is large it's almost impossible to zoom in and out after a certain point.

**Comment by j9liu** [comment]
Hi @engineerhe,

Unfortunately, there is no way to adjust the scroll wheel sensitivity in the Editor. But you can try these options to better navigate the scene. (I'm using Windows, so you may have to look up what the controls are for MacOS if you use that.)
1. If you want to focus on a specific game object, you can bring it into view by **double-clicking it in the Hierarchy** window, or by selecting it and pressing **F**. You can also press **Shift + F**. This is used to lock onto a game object so that the camera follows it as it moves. Usually it zooms further in than just pressing F, because it zooms in on the position specified by the object's **Transform**.
2. Hold the **Alt** key on your keyboard as you press the **right mouse button**. This will allow you to zoom in and out with your mouse.
3. Increase the camera speed, then use the **arrow keys** to move forward towards your tileset. The longer you hold the arrow keys, the faster the camera will travel.

For your second question, you could always decrease the far clip value in the scene. But try setting the **Maximum Cached Bytes** to 0 for your tilesets in the **Inspector** window, that might help.
![image](https://user-images.githubusercontent.com/32226860/210825972-83515f97-e05b-428b-90f2-d909c401066c.png)

**Comment by j9liu** [comment]
Hi @engineerhe,

Unfortunately, there is no way to adjust the scroll wheel sensitivity in the Editor. But you can try these options to better navigate the scene. (I'm using Windows, so you may have to look up what the controls are for MacOS if you use that.)
1. If you want to focus on a specific game object, you can bring it into view by **double-clicking it in the Hierarchy** window, or by selecting it and pressing **F**. You can also press **Shift + F**. This is used to lock onto a game object so that the camera follows it as it moves. Usually it zooms further in than just pressing F, because it zooms in on the position specified by the object's **Transform**.
2. Hold the **Alt** key on your keyboard as you press the **right mouse button**. This will allow you to zoom in and out with your mouse.
3. Increase the camera speed, then use the **arrow keys** to move forward towards your tileset. The longer you hold the arrow keys, the faster the camera will travel.

For your second question, you could always decrease the far clip value in the scene. But try setting the **Maximum Cached Bytes** to 0 for your tilesets in the **Inspector** window, that might help.
![image](https://user-images.githubusercontent.com/32226860/210825972-83515f97-e05b-428b-90f2-d909c401066c.png)

**Comment by engineerhe** [comment]
@j9liu Thank you very much for your patient answer. I will have a try

**Comment by engineerhe** [comment]
dear @j9liu ,
  I want to ask you one last question, I promise.
  Can you help me explain the reason for this, as shown below
![Y7T5_KTX5@HLQZRRNU(__78](https://user-images.githubusercontent.com/39166385/210969707-ab7d981f-2ca8-4724-a6e9-78fd6a110108.png)

**Comment by j9liu** [comment]
Hi @engineerhe ,

I'm not sure what the problem is from a glance. Does this happen with just any `Cesium3DTileset`, or is it because you have a lot of them in the scene?

**Comment by engineerhe** [comment]
Dear @j9liu ,
This fatal error usually happens when I set the camera while browsing the scene, not all Cesium3DTileset have this problom.No matter how I set up the camera, there's a high probability of this happening, right. This means that when I'm editing the scene, I can't set any parameters to the camera.So I feel strange and ask you the reason about it

**Comment by engineerhe** [comment]
Dear @j9liu ,
Today I tested it in the scene view and the game view respectively. Maybe it has nothing to do with the camera Settings, but it crashes frequently. The following two screenshots are errors in the game view and the scene view respectively.And the Cesium3dtiles's address I tested was " http://223.243.132.41:5002/maspipemodel/phase1/model1/tileset.json"
![image](https://user-images.githubusercontent.com/39166385/211487489-46ead2ec-0265-4dbc-8f5b-3e33ffd4ba74.png)
![image](https://user-images.githubusercontent.com/39166385/211487907-db13bf98-69fd-49bc-9b6a-27b41e7b7357.png)

**Comment by engineerhe** [comment]
By the way, I didn't do anything while I was testing, just navigating the scene.

**Comment by j9liu** [comment]
Hi @engineerhe ,

Yeah I imagine that the camera settings don't actually have much to do with the tile loading. In [cesium-native](https://github.com/CesiumGS/cesium-native) (which Unity is built on), the clipping planes are treated as 0 and infinity, basically, so changing the Unity camera's clipping planes shouldn't actually have an effect on tile loading.

May I know what operating system and GPU you're working with? If the data is publicly available I will try to look into it when I get a chance

**Comment by engineerhe** [comment]
Dear @j9liu ,
My OS is win10 Professional and the GPU is NVIDIA RTX 3060.The data I give is publicly accessible.Finally, thank you very much for your guidance.
