### ISSUE TITLE
Cesium Georeference wrong altitude

### ISSUE THREAD

**Issue by Champi67** [CesiumGS/cesium-unity#199]
Hello,

I think there is something incorrect about the altitude data. I've tried different places in the world and the given altitude looks like offseted from some meters.
To talk with an example, i've taken a known place. The Eiffel Tower in Paris.

> latitude: 48.858093
> longitude: 2.294694
> altitude over the see level: 33.5m

I've added Cesium stuff in the Unity scene, CesiumGeoreference has Position to 0,0,0 in Unity, Cesium World Terrain has position to 0,0,0 in Unity and I'm using the default asset. In CesiumGeoreference script I've added Lat, Long, Alt given previously.
But in Unity world coordinates, the ground lvl is not equals to 33.5m or 0m, it is something like 52.33m, I've added a cube colliding to it to check.
![image](https://user-images.githubusercontent.com/124343882/216560079-7b43c826-fa33-4be7-ae64-f2030996244b.png)

The question is, is it an issue in how altitude is calculated ?
Or maybe, Cesium has an internal mechanism adding some offset depending a formula to avoid some weird effect ?

I saw this behavior in V0.1.2 and in V0.2.0
Thanks in advance,

**Comment by j9liu** [comment]
Hi @Champi67,

The `Height` value refers to the height above the `WGS84` ellipsoid, which Cesium uses to georeference and position objects. This ellipsoid is a model that only approximates the shape of the Earth; it does not account for irregularities in the Earth's surface, and it does not necessarily correspond to height above sea level.

If you'd like to get the true altitude of a point above the terrain, you can use `Physics.Raycast` to get the height of the terrain from that point (assuming `Create Physics Meshes` is checked in the `Cesium3DTileset` component). Alternatively, if you're trying to place an object, you can use a `CesiumGlobeAnchor` so that it stays "anchored" to the desired altitude above the Earth. The `Height` it uses may not necessarily correspond to the actual distance above the terrain.

**Comment by j9liu** [comment]
I'm closing this issue, but in the future, feel free to direct your questions to the [Cesium community forum](https://community.cesium.com/c/cesium-for-unity/13). It's likely that other people will have asked similar questions, and they may be able to answer yours!
