### ISSUE TITLE
See Geoserver/Open Layers information in Hololens 2

### ISSUE THREAD

**Issue by cafigz** [CesiumGS/cesium-unity#348]
Hi there, I was wondering if anyone has ever worked with Geoserver/Open Layers in MRTK/Hololens 2.
If yes, any one can point me in the right direction please?
I'm trying to access to a Geoserver and see the information in real-time, superimposed in the real world.

Best regards!

**Comment by kring** [comment]
You can overlay raster maps from Geoserver (or any WMS server) on terrain using the Web Map Service Raster Overlay component. If you're literally asking about using Open Layers in Unity, I don't know how that might be done and you're probably better off taking it to a more general Unity forum.

I'm going to close this because I don't think there's anything actionable in Cesium for Unity here. If you want to discuss further, please do so in the [community forum](https://community.cesium.com/c/cesium-for-unity/13).
