### ISSUE TITLE
Scale Changes Y Location

### ISSUE THREAD

**Issue by markgrossnickle** [CesiumGS/cesium-unity#369]
We are trying to use CesiumGeoreference.scale as our zoom on bing maps. When we change this value the zoom works correctly but the Y position of the map goes up and down. I've used bing maps directly in the past and had a similar issue where the hack fix was to find the lowest vertex in the terrain and set that as our Y offset. 

Do you have any similar functionality? Any way we can set the scale without the map sinking down or raising up? 

Or perhaps a way I can access the mesh and calc the vert locations myself?

**Comment by kring** [comment]
Please post questions to the [community forum](https://community.cesium.com/c/cesium-for-unity/13). We use GitHub for bug reports and concrete feature requests.

We don't have any built-in functionality like you're describing. The model should scale around the georeference origin, so if you put that "on" terrain at a particular point, then that point should stay at zero while higher or lower terrain moves nearer or farther as the scale changes.

Why use scale to zoom, though? Rather than either moving the camera or changing its field of view?

**Comment by markgrossnickle** [comment]
Use case is similar to this: https://github.com/microsoft/MapsSDK-Unity where you have a map sitting on a table. The problem is/was that as you scale the map then drops below the table and floor or raises above your head.  I scaled the height now with the geoference's scale and that seems to be working though I'm not sure if that is skewing things are not along the Y axis.
